app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// root
Route::get('/', 'StaticPagesController@welcome')->before('guest');

//header
Route::post('utils/search','UtilsController@search');
Route::get('utils/advancedSearch','UtilsController@advancedSearch');
Route::post('utils/advancedSearch','UtilsController@advancedSearch');
Route::get('utils/search','UtilsController@search');

//s busquedaUsuario
Route::post('utils/busquedaUsuario', function(){
	$buscador = Input::get('buscador');
	$found = ViewHelpers::userSearchEach($buscador);
	return View::make('utils.busquedaUsuario')-> with('found',User::whereIn('id',$found)->paginate(3))-> with ('buscador', $buscador);
});
// busquedaApuntes
Route::post('utils/busquedaApuntes', function(){
	$buscador = Input::get('buscador');
	$found = ViewHelpers::resourcesSearchEach($buscador);
	return View::make('utils.busquedaApuntes')-> with('found',Resource::whereIn('id',$found)->paginate(3))-> with ('buscador', $buscador);
});

// StaticPages
Route::get('condiciones', 'StaticPagesController@cond');
Route::get('politicas', 'StaticPagesController@policy');
Route::get('about', 'StaticPagesController@about');
Route::get('contacto', 'StaticPagesController@contact');
Route::get('faq', 'StaticPagesController@faq');

// Users
Route::get('usuarios', 'UserController@index');
Route::get('registrate', 'UserController@create');
Route::post('registrate', 'UserController@create'); // from welcome
Route::post('users', 'UserController@store'); // para que create haga post en store (registra usuario)
Route::get('usuarios/{username}', 'UserController@show')->where('username','[A-Za-z0-9]+');
Route::get('usuarios/{username}/followers', 'UserController@followers')->where('username','[A-Za-z0-9]+');
Route::get('usuarios/{username}/following', 'UserController@following')->where('username','[A-Za-z0-9]+');
Route::get('usuarios/{username}/sugerencias','UserController@sugerencias')->where('username','[A-Za-z0-9]+');

//Rankings
Route::get('rank','UserController@rankView');
Route::post('showResults','UserController@showResults');

// SESSIONS
Route::get('login', '')->before('auth');
Route::post('login', 'SessionController@login');
Route::get('perfil', 'SessionController@profile')->before('auth');
Route::get('notificaciones', 'SessionController@notificaciones')->before('auth');
Route::get('salir', 'SessionController@logout')->before('auth');
// follow & unfollow
Route::post('usuarios/{username}/follow', 'SessionController@follow');
Route::post('usuarios/{username}/unfollow', 'SessionController@unfollow');
// fav user
Route::post('usuarios/{username}/fav', 'SessionController@fav');
Route::post('usuarios/{username}/unfav', 'SessionController@unfav');
// defav user
Route::post('usuarios/{username}/defav', 'SessionController@defav');
Route::post('usuarios/{username}/undefav', 'SessionController@undefav');
// Session#update(profile)
Route::post('updateData', 'SessionController@updateData');
Route::post('updatePassword', 'SessionController@updatePassword');
Route::post('updateDesc', 'SessionController@updateDesc');
Route::get('deleteUser', 'SessionController@destroy')->before('auth');

// CATEGORIES
Route::post('postCategory', 'CategoryController@store');
Route::get('usuarios/{username}/categorias', 'CategoryController@index')->where('username','[A-Za-z0-9]+');
Route::get('usuarios/{username}/categorias/{idOrSlug}', 'CategoryController@show')->where('username','[A-Za-z0-9]+')->where('idOrSlug','[a-z0-9\-]+');
Route::get('usuarios/{username}/categorias/{idOrSlug}/editar', 'CategoryController@edit')->where('username','[A-Za-z0-9]+')->where('idOrSlug','[a-z0-9\-]+')->before('loged_in');
Route::get('usuarios/{username}/categorias/{idOrSlug}/eliminar', 'CategoryController@delete')->where('username','[A-Za-z0-9]+')->where('idOrSlug','[a-z0-9\-]+')->before('loged_in');
Route::post('usuarios/{username}/categorias/{idOrSlug}/update', 'CategoryController@update');

// RESOURCES
Route::get('usuarios/{username}/new','ResourceController@create_or_edit')->where('username','[A-Za-z0-9]+')->before('auth');
Route::post('usuarios/{username}/new','ResourceController@create_or_edit')->where('username','[A-Za-z0-9]+');
Route::post('usuarios/{username}/crear','ResourceController@store')->where('username','[A-Za-z0-9]+');
Route::get('usuarios/{username}/recursos/{idOrSlug}','ResourceController@show')->where('username','[A-Za-z0-9]+')->where('idOrSlug','[a-z0-9\-]+');
Route::get('usuarios/{username}/recursos/{idOrSlug}/editar', 'ResourceController@create_or_edit')->where('username','[A-Za-z0-9]+')->where('idOrSlug','[a-z0-9\-]+')->before('loged_in');
Route::get('usuarios/{username}/recursos/{idOrSlug}/deletePDF', 'ResourceController@deletePDF')->where('username','[A-Za-z0-9]+')->where('idOrSlug','[a-z0-9\-]+')->before('loged_in');
Route::get('usuarios/{username}/recursos/{idOrSlug}/eliminar', 'ResourceController@delete')->where('username','[A-Za-z0-9]+')->where('idOrSlug','[a-z0-9\-]+')->before('loged_in');
Route::post('usuarios/{username}/recursos/{idOrSlug}/update', 'ResourceController@update');
Route::post('usuarios/{username}/recursos/{idOrSlug}/report','ResourceController@report')->where('username','[A-Za-z0-9]+')->where('idOrSlug','[a-z0-9\-]+')->before('auth');
// fav resource
Route::post('usuarios/{username}/recursos/{idOrSlug}/fav', 'ResourceController@favRes');
Route::post('usuarios/{username}/recursos/{idOrSlug}/defav', 'ResourceController@unfavRes');
// escritorio personal
Route::post('usuarios/{username}/recursos/{idOrSlug}/add', 'ResourceController@addRes');
Route::post('usuarios/{username}/recursos/{idOrSlug}/remove', 'ResourceController@removeRes');

// FACEBOOK LOGIN
Route::get('login/fb', 'FacebookController@login');
Route::get('login/fb/callback', 'FacebookController@callback');
Route::get('login/fb/{username}/delete', 'FacebookController@deleteLogin')->where('username','[A-Za-z0-9]+')->before('loged_in');
Route::post('login/fb/{username}/update', 'FacebookController@update')->where('username','[A-Za-z0-9]+')->before('loged_in');

// TWITTER LOGIN
Route::get('twitter/login', 'TwitterController@login');
Route::get('twitter/callback', 'TwitterController@callback');
Route::get('twitter/login/{username}/delete', 'TwitterController@deleteLogin')->where('username','[A-Za-z0-9]+')->before('loged_in');
Route::post('twitter/login/{username}/update', 'TwitterController@update')->where('username','[A-Za-z0-9]+')->before('loged_in');

//EMAIL NOTIFICATIONS
Route::get('notifications/{username}/enableAll','NotificationsController@enableAll')->where('username','[A-Za-z0-9]+')->before('loged_in');
Route::get('notifications/{username}/disableAll','NotificationsController@disableAll')->where('username','[A-Za-z0-9]+')->before('loged_in');
Route::post('notifications/{username}/enableOrDisableNotification','NotificationsController@enableOrDisableNotification')->where('username','[A-Za-z0-9]+')->before('loged_in');

Route::post('/notifications', function(){
	return View::make('layouts._notifications');
});
Route::post('/countnotifications', function(){
	return Auth::user()->notifications()->unread()->count();
});

Route::post('/popnotifications', function(){
	$userid = Input::get('userid');
	return View::make('layouts._popnotifications')->with("noti", ViewHelpers::popNotifications($userid));
});


// PASSWORDS
Route::controller('password', 'RemindersController');

// ACCESS (deprecated)
// Route::post('access/send', 'AccessController@sendAccess');
// Route::get('access/unete/{token}', 'AccessController@create')->before('guest');
// Route::post('users', 'AccessController@store');

// UTILS
Route::get('actualmente','UtilsController@now');
//Route::post('users/create', 'UserController@create'); // para que welcome haga post en create
//Route::post('usuarios/{username}/addCat','UtilsController@addCat')->where('username','[A-Za-z0-9]+')->before('auth');

Route::get('/caca', function () {
   
});

app/models/Resource.php
<?php

	Validator::resolver(function($translator, $data, $rules, $messages)
	{
	  return new CustomValidator($translator, $data, $rules, $messages);
	});

	Validator::extend('validYoutubeURL', function($attribute, $value, $parameters)
	{
		$parts = parse_url($value);
		return !empty($parts['host']) && ($parts['host'] == 'www.youtube.com' || $parts['host'] == 'www.youtube.be') && !empty($parts['query']);
	});

	class Resource extends Model {

		/* ENUM TYPE */
		const Publico = 'pu';
	  const Privado = 'pr';
	  const Registrado = 'r';

	  const Secundaria = 'Secundaria';
	  const Bachillerato = 'Bachillerato';
	  const Universidad = 'Universidad';
	  const Otro = 'Otro';

		/**
		 * The database table used by the model.
		 *
		 * @var string
		 */
		protected $table = 'resources';

		public function beforeSave() {
		    //$this->title = strtolower($this->title);
		    //$this->title = ucfirst($this->title);

		    $this->keywords = strtolower($this->keywords);
		    $this->keywords = CustomValidator::stripAccents($this->keywords);
		    
		    return true;
		    //or don't return nothing, since only a boolean false will halt the operation
		}
		public function beforeUpdate() {
	    return $this->beforeSave();
		}	

		/*Mass asignment*/
		protected $fillable = array('title', 'short_desc','youtube_url', 'curso', 'keywords', 'category_id', 'visibility','slug');
		/*No Mass assignment*/
		protected $guarded = array('id', 'favs');

		/*Validation rules*/
		public static $rules = array(
	    'title'    => array('required','between:3,50','resourceTitleNotRepeated:user_id'),
	    'short_desc' 	=> array('required','max:140'),
	    'youtube_url' => array('between:3,100','validYoutubeURL'),
	    'keywords'    => array('regex:/\A[a-zA-Záéíóú\,]+\Z/')
	  );
	  public static $updateRules = array(
	    'title'    => array('required','between:3,50','resourceTitleNotRepeated:user_id,id'),
	    'short_desc' 	=> array('required','max:140'),
	    'youtube_url' => array('between:3,100','validYoutubeURL'),
	    'keywords'    => array('regex:/\A[a-zA-Záéíóú\,]+\Z/')
	  );

		/* Custom error messages TODO*/
	  public static $messages = array(
	    'required' => 'El campo :attribute no puede estar vacío.',
	    'between' => 'El :attribute debe estar entre :min y :max.',
	    'max' => 'El :attribute no puede tener más de :max carácteres.',
	    'resource_title_not_repeated' => 'Ya tienes un recurso con este titulo.',
	    'regex' => 'El :attribute no tiene un formato válido.',
	    'valid_youtube_ur_l' => 'La URL de Youtube no tiene el formato correcto.'
	  );

	  /**
		 * Resource parent category
		 */
		public function category()
		{
		  return $this->belongsTo('Category', 'category_id');
		}
		 /**
		 * Resource parent user
		 */
		public function user()
		{
		  return $this->belongsTo('User', 'user_id');
		}
		/**
		 * Resource faver relationship
		 */
		public function favers()
		{
		  return $this->belongsToMany('User', 'resources_favs', 'resource_id', 'user_id');
		}
		/**
		 * Resource adders relationship
		 */
		public function adders()
		{
		  return $this->belongsToMany('User', 'resources_personal', 'resource_id', 'user_id');
		}

		// ----------> BOOLEANS <-----------
		// to know if the resource is faved by somebody
		public function faved_by($id)
		{
			return $this->favers->contains($id);
		}
		// to know if the resource is added by somebody
		public function added_by($id)
		{
			return $this->adders->contains($id);
		}

		// ----------> FUNCIONES AUXILIARES <-----------
		public function getTextAttribute()
		{
			$path = public_path().'/files/usuarios/'.$this->user->username.'/'.$this->category->id.'/'.$this->attributes['id'];
			$file = fopen( $path.'/text', "r" );
			if( $file == false )
			{
			   echo ( "Error in opening file" );
			   exit();
			}
			$filesize = filesize( $path.'/text' );
			$filetext = fread( $file, $filesize );

			fclose( $file );
			return $filetext;
		}
		public function getMiniAttribute()
		{
			return strip_tags(Str::limit($this->text,400));
		}
		public function getYoutubeIDAttribute()
		{
			$youtube_url = $this->attributes['youtube_url'];
			// We get an array of index-value
			parse_str( parse_url( $youtube_url, PHP_URL_QUERY ), $url_vars );
			// We return only the id
			// compatibilidad con base de datos donde solo se encuentre el ID
			return empty($url_vars['v']) ? $youtube_url : $url_vars['v'];
		}
		public function colorFavs()
		{
			if($this->attributes['favs'] > 0)
				return 'style="color:green;background:#D8D8D8;"';
			else
				return 'style="color:green;background:#D8D8D8;"';
		}
}

app/controllers/CategoryController.php
<?php

class CategoryController extends BaseController {

	public function store()
	{
		$params=Input::only('title','short_desc');
		$user = Auth::user();

		// ----------> Creación de categoria <------------
		$category = new Category;
		$category->user_id = $user->id;
		$category->fill($params);
		$category->slug = Str::slug($params['title']);

		if ($category->save()) 
		{
			return Redirect::back()->with('success_message', 'La categoría ha sido creada con éxito.');
    } 
    else 
    {
    	return Redirect::back()->withErrors($category->errors());
    }
	}

	public function index($username)
	{
		$user = User::findByUsernameOrFail($username);
		$paginator = Category::where('user_id', $user->id)->orderBy('created_at', 'desc')->paginate(6);

		$this->layout->content = View::make('categories.index',['user' => $user, 'categories' => $paginator]);
	}

	public function show($username, $idOrSlug)
	{
		$user = User::findByUsernameOrFail($username);
		$category = Category::where('id',$idOrSlug)->orWhere('slug',$idOrSlug)->where('user_id',$user->id)->firstOrFail();

		$visibility = array('foo'); // default value so we dont get null
		if(!Auth::check()) // if you're not loged in you cant see registered and private ones
			array_push($visibility, Resource::Registrado, Resource::Privado);
		else{
			$viewer = Auth::user();
			if($viewer->username != $username) // you cant see private resources
				array_push($visibility, Resource::Privado);
		}

		$paginator = Resource::where('user_id', $user->id)->where('category_id', $category->id)->whereNotIn('visibility', $visibility)->orderBy('created_at', 'desc')->paginate(6);

		$this->layout->content = View::make('categories.show',[ 'user' => $user, 'category' => $category, 'id' => $category->id, 'resources' => $paginator]);
	}

	public function edit($username, $idOrSlug)
	{
		$user = User::findByUsernameOrFail($username);
		$category = Category::where('id',$idOrSlug)->orWhere('slug',$idOrSlug)->where('user_id',$user->id)->firstOrFail();
		$paginator = Resource::where('user_id', $user->id)->where('category_id', $category->id)->orderBy('created_at', 'desc')->paginate(6);

		$this->layout->content = View::make('categories.edit',[ 'user' => $user, 'category' => $category, 'id' => $category->id, 'resources' => $paginator]);
	}

	public function update($username, $idOrSlug)
	{
		$user = User::findByUsernameOrFail($username);
		$category = Category::where('id',$idOrSlug)->orWhere('slug',$idOrSlug)->where('user_id',$user->id)->firstOrFail();

		$params = Input::only('title', 'short_desc');
		$params = array_add($params, 'slug', Str::slug($params['title']));

		if($category->update($params))
		{
			return Redirect::to('/usuarios/'.$username.'/categorias/'.$idOrSlug)->with('success_message', 'La categoria ha sido actualizada con exito');
		}
		else
		{
			return Redirect::back()->withErrors($category->errors());
		}
	}

	public function delete($username, $idOrSlug)
	{
		$user = User::findByUsernameOrFail($username);
		$category = Category::where('id',$idOrSlug)->orWhere('slug',$idOrSlug)->where('user_id',$user->id)->firstOrFail();
		ControllerHelpers::rrmdir(public_path().'/files/usuarios/'.$username.'/'.$category->id);
		foreach($category->resources as $resource){
			ControllerHelpers::remove_resource_rows($resource);
		}

	  $category->delete();

	  return Redirect::to('/usuarios/'.$username.'/categorias')
	            ->with('success_message', 'La categoria ha sido eliminada con exito.');
	}

}

app/views/categories/edit.blade.php
@section('title', 'Editar '.$category->title)

@section('header')
@parent
<!-- HEADER !-->
<form method="post" action="update" id="category">
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row"  style="padding:0 15px 0 15px;">
      <div class="media">
  		  <a class="pull-left col-md-1">
  		    <img class="media-object" src='{{$user->gravatar(100)}}'>
  		  </a>
  		  <div class="media-body col-md-7" >
  		    <h3 class="media-heading">
            <div class="col-md-6"><input type="text" value="{{ null!==Input::old('title') ? Input::old('title') : $category->title }}" class="form-control" name="title"></input></div> - <small><a href="/usuarios/{{$user->username}}">{{ '@'.$user->username }}</a></small>
          </h3>
          <br>
  		    <textarea name="short_desc" class='form-control input-lg' 
            form="category" placeholder="Añade una descripción...">{{ null!==Input::old('short_desc') ? Input::old('short_desc') : $category->short_desc }}</textarea>
  		  </div>
  		  <div class="col-md-3 pull-right">
  		  	<ul class="list-group">
  				  <li class="list-group-item">Recursos <span class="badge">{{ $category->resources->count() }}</span> </li>
  				</ul>
          <div class="pull-right">
            <button class="btn btn-primary" type="submit">Guardar</button>
             <a href="eliminar"><button type="button" class="btn btn-danger" onClick="if(confirm('¿Estas seguro de borrar la categoria? Todos los recursos pertenecientes a esta categoria desapareceran.'))
            ;
            else return false;">Eliminar</button></a>
            <a href="../{{$category->slug}}"><button class="btn btn-default" type="button">Cancelar</button></a>      
          </div>
  		  </div>
  		</div>
    </div>
  </div>
</div>
</form>
<!-- FIN HEADER !-->
@endsection

@section('content')
<!-- BODY !-->
<div class="panel panel-default"> 
	<!-- RECURSOS Y PUBLI !-->
	<div class="row" style="margin:0px;padding-top:20px;">
    <!-- PUBLI HERE !-->
    <div class="col-md-2">
      @include('publi/160x600left')
    </div>
    <!-- FIN PUBLI !-->
    <!-- RECURSOS HERE !-->
    <div class="col-md-8">
      <div class="row"  style="margin:0px;padding:0px;">
        @forelse($resources as $res)
    		<div class="col-md-4">
    				<div class="thumbnail">
    					<center><div style="background-color:grey;height:250px;width:90%;"><h3>{{$res->mini}}</h3></div></center>
                <div class="row" style="margin:0px;">
            			<div class="caption">
                    <hr style="margin:0px;">
      				  		<h4><a href='../recursos/{{$res->slug}}'>{{ $res->title }}</a> <span class="badge pull-right"><a data-container="body" style="text-decoration:none;color:white;" data-toggle="popover" data-placement="top" 
            data-content="Cuantos usuarios han hecho Fav en este recurso.">{{$res->favs}}</a></span></h4>
                    <p>{{ $res->short_desc }}</p>
                    @if(Auth::check())
                    <div class="row" style="margin:0px;">
                      @if(!ViewHelpers::loged_in($user->username))
                      <div class="col-md-4">
                        @if($res->faved_by(Auth::user()->id))
                        <form action="../recursos/{{$res->id}}/defav" method="post">
                            <button class="btn btn-success" type="submit" name="defav"><img src='/images/fav.png'> Fav</button>
                        </form>
                        @else
                        <form action="../recursos/{{$res->id}}/fav" method="post">
                            <button class="btn btn-primary" type="submit" name="fav"><img src='/images/fav.png'> Fav</button>
                        </form>
                        @endif
                      </div>
                      @endif
                      <div class="col-md-7"><button class="btn btn-default" role="button">Añadir a..</button></div>
                      <a href="/usuarios/{{$user->username}}/recursos/{{$res->id}}/eliminar"><button class="btn btn-danger btn-sm" onClick="if(confirm('¿Estas seguro de borrar el recurso? El recurso no se podra recuperar.'))
                      ;
                      else return false;">Eliminar</button></a>
                    </div>
                    @endif
                    <hr style="margin:10px;">
                    <div class="pull-right"><small>{{ViewHelpers::time_ago($res->updated_at)}}</small></div>
      				  	</div>
                </div>
    				</div>
    		</div>
        @empty
        Todavía no has añadido recursos
        @endforelse
      </div>
    </div>
    <!-- FIN RECURSOS HERE !-->
    <!-- PUBLI HERE !-->
    <div class="col-md-2">
      @include('publi/160x600right')
    </div>
    <!-- FIN PUBLI !-->
	</div>
  <!-- FIN RECURSOS Y PUBLI !-->
  <center>{{$resources->links()}}</center>
</div>
<!-- FIN BODY !-->
@endsection

app/views/categories/index.blade.php
@section('title', 'Categorías de '.$user->username)

@section('header')
@parent
<div class="container-fluid bodyheader">
	<!-- avatar !-->
	<div class="col-md-1" style="margin:0px;padding:0px;">
		<img src="{{$user->gravatar(100)}}"/>
	</div>
	<!-- FIN avatar !-->
	<!-- info !-->
	<div class="col-md-8" style="margin:0px;">
		<h4>{{$user->completeName}} - <small><a href="/usuarios/{{$user->username}}">@{{{$user->username}}}</a></small></h4>
		<div class="well well-sm">{{$user->short_desc}}</div>
		<a><small>Reportar usuario</small></a>
	</div>
	<!-- FIN info !-->
	<!-- estadisticas !-->
	<div class="col-md-3">
		<ul class="list-group">
			<li class="list-group-item">Categorias: <span class="badge">{{$user->categories->count()}}</span></li>
			<li class="list-group-item">Recursos: <span class="badge">{{$user->resources->count()}}</span></li>
		</ul>
		<small class="pull-right">Ultima actualizacion: @if($user->resources->last()) {{ViewHelpers::time_ago($user->resources->last()->created_at)}} @else Nunca @endif</small>
	</div>
	<!-- FIN estadisticas !-->
</div>
@endsection

@section('content')
<!-- BODY !-->
<div class="row col-centered bodypanel">
	@include('publi/160x600left')
	<!-- panel central !-->
	<div class="col-md-8">
		<h4>Categorias de {{$user->username}}</h4> <br>
			<!-- accordeon !-->
			<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
			  @forelse($categories as $cat)
				  <div class="panel panel-default">
				    <div class="panel-heading" role="tab" id="heading{{$cat->id}}">
				      <h4 class="panel-title">
				        <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{$cat->id}}" aria-expanded="true" aria-controls="collapse{{$cat->id}}">
				          {{$cat->title}} <span class="pull-right badge">{{$cat->resources->count()}}</span>
				        </a>
				      </h4>
				    </div>
				    <div id="collapse{{$cat->id}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{$cat->id}}">
				      <!-- recursos de categoria !-->
				      <div class="panel-body">
				      	<p>Descripcion:</p>
				      	<p style="margin-left:10px;">{{$cat->short_desc}}</p>
				      	<p>Ultimos recursos:</p>
								@forelse(ViewHelpers::category_resources($cat,5) as $res)
									<a class="list-group-item" href="{{ViewHelpers::resource_link($res)}}">
										{{$res->title}} <small class="pull-right">{{ViewHelpers::time_ago($res->created_at)}}</small>
									</a>
								@empty
									<p>El usuario no ha añadido ningun recurso...</p>
								@endforelse
				      </div>
				      <!-- FIN recursos de categoria !-->
				    </div>
				  </div>
			  @empty
			  	<p>El usuario no ha añadido categorias...</p>
			  @endforelse
			</div>
		<!-- FIN accordeon !-->
		<center>{{$categories->links()}}</center>
	</div>
	<!-- FIN panel central !-->
	@include('publi/160x600right')
</div>
<!-- FIN BODY !-->
@endsection

app/views/categories/show.blade.php
@section('title', $user->username.'@'.$category->title)

@section('header')
@parent
<div class="container-fluid bodyheader">
  <!-- avatar !-->
  <div class="col-md-1" style="margin:0px;padding:0px;">
    <img src="{{$user->gravatar(100)}}"/>
  </div>
  <!-- FIN avatar !-->
  <!-- info !-->
  <div class="col-md-8" style="margin:0px;">
    <h4>{{$category->title}} - <small><a href="/usuarios/{{$user->username}}">@{{{$user->username}}}</a></small></h4>
    <div class="well well-sm">{{$category->short_desc}}</div>
    <a><small>Reportar usuario</small></a>
  </div>
  <!-- FIN info !-->
  <!-- estadisticas !-->
  <div class="col-md-3">
    <ul class="list-group">
      <li class="list-group-item">Recursos: <span class="badge">{{$category->resources->count()}}</span></li>
      <li class="list-group-item">
        <div class="row">
          <div class="fb-share-button col-md-6" data-href="{{Request::url()}}" data-layout="button_count"></div>
          <div><a href="https://twitter.com/share" class="twitter-share-button col-md-6" data-via="PassItEDU" data-lang="es">Twittear</a></div>
        </div>
      </li>
    </ul>
    @if(ViewHelpers::loged_in($user->username))
    <div class="pull-right">
      <a href="{{$category->slug}}/editar"><button class="btn btn-info">Editar</button></a>
    </div>
    @else
    <small class="pull-right">Ultima actualizacion: @if($category->resources->last()) {{ViewHelpers::time_ago($category->resources->last()->created_at)}} @else Nunca @endif</small>
    @endif
  </div>
  <!-- FIN estadisticas !-->
</div>
@endsection

@section('content')
<!-- BODY !-->
<div class="row col-centered bodypanel"> 
  @include('publi/160x600left')
  <!-- RECURSOS HERE !-->
  <div class="col-md-8" >
    @include('partials/_showrecurso')

    <center>{{$resources->links()}}</center>
  </div>
  <!-- FIN RECURSOS HERE !-->
  @include('publi/160x600right')
</div>
<!-- FIN BODY !-->
@endsection